# -------------------- Parameters --------------------

input_counts : "data_input/WT_valid_may2025_2.csv"
input_controls : "data_input/genes_zGE_official.csv"
output_dir : "output"
index_scheme : 2  # both replicas if 2; 1 if only one replica
d       : 4  # number of gRNAs per gene
 
ssc     : 1 #small sample correction count

alf     : 0.06  # significance level of right-left tail of distribution
st      : -20
en      : 10
step    : 0.05
start_end : [st, en]

# Patterns for filtering 
pat1    : 'chr'
pat2    : 'Non'
n       : 3

cond1   : 'F'
cond2   : 'M'
condz   : 'zGE_FM'
cond11  : 'Interg_F'
cond12  : 'NT_F'
condz1  : 'zGE_F'
condz2  : 'zGE_M'

indiv   : 'FM'  
cond_id : 'F_M'

sfdr_corr : 0.0001

# for LFC (Volcano)
thr_lfchz : 1.7
thr_lfcdz : -1.7
