# -------------------- Parameters --------------------

input_counts : "demo_data/milan_raw.csv"
input_controls : "demo_data/genes_zGE_official_milan.csv"
output_dir : "output_milan/IR_int"
index_scheme : 2  # 2 if two conditions; 1 if only one condition
d       : 10  # number of gRNAs per gene
rep     : 4 # number of replicates per condition
alf     : 0.06  # significance level of right-left tail of distribution
st      : -10 #
en      : 10
step    : 0.05
thr_lfchz : 1.7 # LCF threshold
keep_counts : [1, 4, 10] 
control : "Intergenic" # choice between Intergenic, Non-targetting or zGE

# Patterns for filtering 
pat1    : 'chr' #Intergenic filtering
pat2    : 'Non' #Non-targetting filtering
cond1   : 'IR' #condition 1
cond2   : 'T0' #condition 2
rep_pairs : ['60159', '60160', '60161', '60162']



